get: 
  is: [ isCommentLikes ]
  description: Get information about the likes for a comment. Also used to like a comment.
  responses: 
    200: 
post: 
  description: Get information about the likes for a comment. Also used to like a comment.
  responses: 
    200: 
head: 
  is: [ isCommentLikes ]
  description: Get information about the likes for a comment. Also used to like a comment.
