get: 
  description: Access the associated actions capability of a feed element.
  responses: 
    200: 
head: 
  description: Access the associated actions capability of a feed element.
  responses: 
    200: 
